### ISSUE TITLE
Uncaught Server Exception

### ISSUE THREAD

**Issue by jmyera** [frappe/erpnext_documentation#254]
I have tried to install the **erpnext_documentation** application but have no good results, I would appreciate any guidance.

> Environment: **[ERPNext Docker](https://github.com/frappe/frappe_docker)**
> ERPNext: v12.18.0 (version-12)
> Frappe Framework: v12.15.0 (version-12)

Bench installed and running with a first ERPNext site.

**erpnext_documentation** installation steps:

```
bench get-app erpnext_documentation
bench get-app frappe_theme
bench new-site site-name
bench --site site-name install-app erpnext_documentation
bench start
```

![Uncaught Server Exception](https://user-images.githubusercontent.com/3195070/109190909-e625c700-7795-11eb-8e8d-9e2948b06a87.png)

```
Traceback (most recent call last):
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 80, in render_template
    return get_jenv().from_string(template).render(context)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "<template>", line 14, in root
  File "/workspace/development/frappe-bench/apps/frappe/frappe/./templates/web.html", line 15, in root
    {% block page_container %}
  File "/workspace/development/frappe-bench/apps/frappe/frappe/./templates/base.html", line 42, in root
    {{ head_include or "" }}
  File "/workspace/development/frappe-bench/apps/frappe/frappe/./templates/web.html", line 92, in block_content
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 440, in call
    return __context.call(__obj, *args, **kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/./templates/web.html", line 43, in macro
    {% endmacro %}
  File "/workspace/development/frappe-bench/apps/frappe/frappe/./templates/web.html", line 122, in block_page_container
  File "<template>", line 29, in block_page_content
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 438, in call
    if not __self.is_safe_callable(__obj):
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 340, in is_safe_callable
    return not (getattr(obj, 'unsafe_callable', False) or
jinja2.exceptions.UndefinedError: 'web_blocks' is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/development/frappe-bench/apps/frappe/frappe/website/render.py", line 50, in render
    data = render_page_by_language(path)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/website/render.py", line 177, in render_page_by_language
    return render_page(path)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/website/render.py", line 193, in render_page
    return build(path)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/website/render.py", line 200, in build
    return build_page(path)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/website/render.py", line 218, in build_page
    html = frappe.render_template(context.source, context)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 82, in render_template
    throw(title="Jinja Template Error", msg="<pre>{template}</pre><pre>{tb}</pre>".format(template=template, tb=get_traceback()))
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 377, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 356, in msgprint
    _raise_exception()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 316, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: <pre>{% extends "templates/web.html" %}
			{% block page_content %}
---
full_width: 1
title: ERPNext Documentation
---

{% from "templates/includes/macros.html" import cards %}

{{ web_blocks([
	{
		'template': 'Hero',
		'values': {
			'title': 'ERPNext Documentation',
			'subtitle': 'ERPNext is a comprehensive business solution with features from Financial Accounting to Portals.'
		},
		'add_bottom_padding': 0
	}
]) }}

<div class="container section-padding-bottom">
	{{ cards([
		{
			'title': 'Manual in English',
			'content': 'The ERPNext Manual covers everything you want to know about configuring and using ERPNext',
			'link': '/docs/user/manual/en'
		},
		{
			'title': 'Handbuch in Deutsch',
			'content': 'Das ERPNext Handbuch enthält alle Informationen zur Konfiguration und Verwendung von ERPNext',
			'link': '/docs/user/manual/de'
		},
		{
			'title': 'Manual en Español',
			'content': 'El Manual ERPNext convierte todo lo que desea saber sobre la configuración y el uso de ERPNext',
			'link': '/docs/user/manual/es'
		}
	]) }}
</div>

<section class="section section-padding-top section-padding-bottom bg-light">
  <div class="container">
    <h2 class="section-title">Developer Documentation</h2>
    <p class="section-description">
      Learn more about Frappe Framework, the framework on which ERPNext is built
	</p>
	{{ cards([
		{
			'title': 'Frappe Framework',
			'content': 'ERPNext is built using the Frappe Framework, a fully featured web framework in Python and Javascript',
			'link': 'https://frappeframework.com/docs'
		},
		{
			'title': 'Tutorial',
			'content': 'Learn the framework architecture by understanding how to build custom apps that can extend ERPNext',
			'link': 'https://frappeframework.com/docs/user/en/tutorial'
		},
		{
			'title': 'Developer API',
			'content': 'Learn about how to build integrations and extensions for ERPNext by using the Developer API',
			'link': 'https://frappeframework.com/docs/user/en/api'
		}
	]) }}
  </div>
</section>

{% set content %}
## Contribution and Feedback

ERPNext is Open Source under the GNU General Public Licence v3 and has
been listed as one of the Best Open Source Softwares in the world by
many online blogs.

You're encouraged to help improve the quality of this documentation, by
sending a pull request on the [GitHub Repository](https://github.com/frappe/erpnext_documentation).
If you would like to have a discussion regarding the documentation,
you can do so [at the forum](https://discuss.erpnext.com).

{% endset %}

{{
	web_blocks([
		{
			'template': 'Markdown',
			'values': {
				'content': content
			}
		}
	])
}}

{{
	web_blocks([
		{
			'template': 'Section with CTA',
			'values': {
				'title': 'Get Started with ERPNext',
				'subtitle': 'ERPNext is used by more than 5000 companies across the world.',
				'cta_label': 'Start Free Trial',
				'cta_url': 'https://erpnext.com/pricing',
				'cta_description': '<a href="https://erpnext.com/contact-form">Contact Us</a>',
				'show_confetti': 1
			},
			'add_top_padding': 0
		}
	])
}}
{% endblock %}</pre><pre>Traceback (most recent call last):
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 80, in render_template
    return get_jenv().from_string(template).render(context)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "<template>", line 14, in root
  File "/workspace/development/frappe-bench/apps/frappe/frappe/./templates/web.html", line 15, in root
    {% block page_container %}
  File "/workspace/development/frappe-bench/apps/frappe/frappe/./templates/base.html", line 42, in root
    {{ head_include or "" }}
  File "/workspace/development/frappe-bench/apps/frappe/frappe/./templates/web.html", line 92, in block_content
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 440, in call
    return __context.call(__obj, *args, **kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/./templates/web.html", line 43, in macro
    {% endmacro %}
  File "/workspace/development/frappe-bench/apps/frappe/frappe/./templates/web.html", line 122, in block_page_container
  File "<template>", line 29, in block_page_content
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 438, in call
    if not __self.is_safe_callable(__obj):
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 340, in is_safe_callable
    return not (getattr(obj, 'unsafe_callable', False) or
jinja2.exceptions.UndefinedError: 'web_blocks' is undefined
</pre>
```

**Comment by jmyera** [comment]
The branch of [Frappe](https://github.com/frappe) must be **develop**.
